[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "42mo47RQAEbdJME5ib5QGWBFJUW2ABBGcnrBxqnRMXRh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/j0nl1/.config/solana/id.json"

[scripts]
test = "npm test"
